DROP SCHEMA if exists VENDAS;

CREATE SCHEMA VENDAS;

USE VENDAS;

DROP TABLE if exists PRODUTOS_PEDIDO;
DROP TABLE if exists PEDIDOS_VENDA;
DROP TABLE if exists CLIENTES;
DROP TABLE if exists PRODUTOS;

CREATE TABLE VENDAS.CLIENTES (
  COD_CLIENTE INT NOT NULL AUTO_INCREMENT,
  NOME_CLIENTE VARCHAR(100) NOT NULL,
  CPF_CNPJ VARCHAR(18) NOT NULL,
  RG_IE VARCHAR(15) NOT NULL,
  LOGRADOURO VARCHAR(50) NULL,
  NUMERO VARCHAR(10) NULL,
  BAIRRO VARCHAR(30) NULL,
  COMPLEMENTO VARCHAR(30) NULL,
  CEP VARCHAR(10) NULL,
  CIDADE VARCHAR(200) NULL,
  UF VARCHAR(2) NULL,
  TELEFONE VARCHAR(40) NULL,
  CONTATO VARCHAR(30) NULL,
  PRIMARY KEY (COD_CLIENTE),
  UNIQUE INDEX COD_CLIENTE_UNIQUE (COD_CLIENTE ASC));

INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Fabiana Elaine Gonçalves', '985.363.110-53', '6786871615', 'Travessa Jambú', '67', 'Luzia', '55645-818', 'Gravatá', 'PE', '55991558845', 'Fabiana');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Lucca Ricardo Rodrigues', '157.813.540-00', '5209020789', 'Rua Luiz Chinablia', '167', 'Santana', '49045-650', 'Aracaju', 'SE', '55999415421', 'Lucca');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Luiz Anthony Sales', '346.142.572-91', '7184789723', 'Avenida Teles Pires', '31', 'Centro', '69908-836', 'Rio Branco', 'AC', '48981225544', 'Luiz');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Geraldo Yuri Kauê Almeida', '782.155.328-02', '3223969217', 'Rua Jardim das Flores', '312', 'Centro', '49045-650', 'Aracaju', 'SE', '62981254578', 'Geraldo');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Maria Catarina Jennifer Silveira', '155.303.386-82', '1745422552', 'Travessa Atitum', '21', 'Pituaçu', '41741-230', 'Salvador', 'BA', '62981459963', 'Maria');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Sara Silvana Rodrigues', '646.410.126-95', '0517301652', 'Rua Naná de Oliveira Pimentel', '234', 'Água Mineral', '64007-500', 'Teresina', 'PI', '67981556325', 'Sara');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Vicente Kauê da Rosa', '199.745.789-06', '6582206877', 'Rua Francisco Carneiro Cavalcante', '53', 'Santana', '98.700-000', 'Ijuí', 'RS', '73984552211', 'Paulo');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Kauê Victor Oliveira', '846.212.224-49', '9781356952', 'Rua da Paz', '127', 'Centro', '69301-440', 'Boa Vista', 'RR', '49991457788', 'João');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Rayssa Benedita Lima', '458.680.398-31', '6615043700', 'CNB 12 Lote 02', '31', 'Centro', '55645-818', 'Gravatá', 'PE', '49999457185', 'Rayssa');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Lara Vitória Almada', '551.626.256-98', '1416149627', 'Rua 24 de Dezembro', '56', 'Trem', '68901-045', 'Macapá', 'AP', '64981669584', 'Lara');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Rita Helena Rocha', '434.841.820-91', '9129548802', 'Rua Pastor Manoel Pereira Lima', '1367', 'Potengi', '59110-972', 'Natal', 'RN', '54981254523', '');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Eliane Luciana Sarah Porto', '212.301.141-06', '4636138880', 'Rua Ricardo de Melo', '985', 'Trindade', '88075-130', 'Florianópolis', 'SC', '48981254545', 'Eliane');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Regina Fernanda Mendes', '907.826.714-38', '2382181303', 'Travessa da Silva', '2342', 'Centro', '64007-500', 'Teresina', 'PI', '54988451451', 'Heloísa');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Fernanda Amanda Jennifer Brito', '657.813.824-29', '3377862366', 'Rua Luiz Marinho dos Santos', '1267', 'Estreito', '88075-130', 'Florianópolis', 'SC', '84981526325', 'Fernanda');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Isabella Andrea Rocha', '184.249.698-04', '2256478394', 'Rua São Leopoldo', '41', 'Centro', '67033-881', 'Ananindeua', 'PA', '62981459315', 'Rocha');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Leandro Joaquim Jesus', '245.717.682-49', '4652669712', 'Praça Frei Félix', '421', 'Centro', '68901-045', 'Macapá', 'AP', '67981549625', 'Joaquim');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Eduarda Antonella Corte Real', '756.446.514-01', '6085230281', 'Rua Madre Tereza de Calcutá', '568', 'Centro', '60861-901', 'Fortaleza', 'CE', '67991545855', 'Jaime');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Evelyn Kamilly Tereza Freitas', '577.848.566-28', '8558536830', 'Quadra O2', '512', 'Centro', '59110-972', 'Natal', 'RN', '67984563254', 'Evelyn');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Joana Carolina Novaes', '485.677.103-59', '8454686894', 'Rua Isolete Ferraz', '715', 'Boa Vista', '60861-901', 'Fortaleza', 'CE', '53981457847', 'Anderson');
INSERT INTO `VENDAS`.`CLIENTES` (`NOME_CLIENTE`, `CPF_CNPJ`, `RG_IE`, `LOGRADOURO`, `NUMERO`, `BAIRRO`, `CEP`, `CIDADE`, `UF`, `TELEFONE`, `CONTATO`) VALUES ('Yuri Paulo Rodrigues', '391.071.426-92', '0888804385', 'Avenida Alameda do Serrano', '981', 'Centro', '59110-972', 'Natal', 'RN', '54981542515', 'Cassio');

CREATE TABLE VENDAS.PRODUTOS (
  COD_PRODUTO INT NOT NULL AUTO_INCREMENT,
  DESCR_PRODUTO VARCHAR(100) NOT NULL,
  PRECO_VENDA DECIMAL(19,6) NOT NULL,  
  PRIMARY KEY (COD_PRODUTO));

INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('SABÃO EM PÓ', '10');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('VASSOURA', '15.5');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('DETERGENTE', '4.5');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('ÁGUA MINERAL', '9.5');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('CHOCOLATE', '7.5');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('PÃO INTEGRAL', '27.5');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('BANANA', '14.85');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('CARNE MOÍDA', '20.95');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('CAMISETA', '10.99');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('CALÇA', '15.5');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('VESTIDO', '24.5');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('BERMUDA', '17.9');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('MACARRÃO', '110');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('ARROZ', '150.95');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('FEIJÃO', '74.5');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('LENTILHA', '27.5');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('SORVETE', '100');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('BATATA', '150');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('LEITE', '154.5');
INSERT INTO `vendas`.`produtos` (`DESCR_PRODUTO`, `PRECO_VENDA`) VALUES ('TOMATE', '67.5');


CREATE TABLE VENDAS.PEDIDOS_VENDA (
  NUM_PEDIDO INT NOT NULL AUTO_INCREMENT,
  DT_EMISSAO DATE NOT NULL,  
  COD_CLIENTE INTEGER NOT NULL,
  VALOR_TOTAL DECIMAL(19,6) NOT NULL,  
  PRIMARY KEY (NUM_PEDIDO),
  INDEX FK_CLIENTE_idx (COD_CLIENTE ASC),
  CONSTRAINT FK_CLIENTE
    FOREIGN KEY (COD_CLIENTE)
    REFERENCES VENDAS.CLIENTES (COD_CLIENTE)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);

CREATE TABLE VENDAS.PRODUTOS_PEDIDO (
  ID_PRODUTO_PEDIDO INT NOT NULL AUTO_INCREMENT,
  NUM_PEDIDO INT NOT NULL,
  COD_PRODUTO INT NOT NULL,
  QUANTIDADE DECIMAL(19,6) NOT NULL,
  VL_UNITARIO DECIMAL(19,6) NOT NULL,
  VL_TOTAL DECIMAL(19,6) NOT NULL,
  PRIMARY KEY (`ID_PRODUTO_PEDIDO`),
  INDEX FK_PEDIDO_idx (NUM_PEDIDO ASC),
  CONSTRAINT FK_PEDIDO
    FOREIGN KEY (NUM_PEDIDO)
    REFERENCES VENDAS.PEDIDOS_VENDA (NUM_PEDIDO)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  INDEX FK_PRODUTO_idx (COD_PRODUTO ASC),
  CONSTRAINT FK_PRODUTO
    FOREIGN KEY (COD_PRODUTO)
    REFERENCES VENDAS.PRODUTOS (COD_PRODUTO)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION
);